### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by mhsung** [sweeneychris/TheiaSfM#66] opened 2016-03-08 03:14 UTC
Hello,

Could someone please give me any hint why the following test cases fail?

The following tests FAILED:
         43 - linear_rotation_estimator_test (OTHER_FAULT)
         62 - two_point_pose_partial_rotation_test (Failed)
         73 - orientations_from_maximum_spanning_tree_test (OTHER_FAULT)

**Comment by sweeneychris** [comment] 2016-03-08 03:33
Can you run the tests individually and provide me the results? For instance:

./bin/linear_rotation_estimator_test --logtostderr

**Comment by mhsung** [comment] 2016-03-08 04:30
Now the second passes, and the followings are results of others:

*** Error in `./bin/linear_rotation_estimator_test': free(): invalid pointer: 0x00000000009a7360 ***
Aborted (core dumped)

*** Error in `./bin/orientations_from_maximum_spanning_tree_test': free(): invalid pointer: 0x0000000001718960 ***
Aborted (core dumped)

My gcc version is:
gcc (Ubuntu/Linaro 4.7.3-12ubuntu1) 4.7.3

**Comment by sweeneychris** [comment] 2016-03-08 16:38
What version of Eigen are you using?

**Comment by mhsung** [comment] 2016-03-08 17:04
I'm using Eigen v3.2.0.

**Comment by sweeneychris** [comment] 2016-03-08 18:00
I can't seem to recreate that bug. Could you please run the following commands and inform me of the output?

cmake .. -DCMAKE_BUILD_TYPE=Debug
make -j
gdb --args ./bin/linear_rotation_estimator_test --logtostderr


then run the program in gdb with "run". And similarly for the orientations_from_maximum_spanning_tree_test

**Comment by sweeneychris** [comment] 2016-03-15 16:54
have you fixed the failing tests? If so, can we close this issue?

**Comment by mhsung** [comment] 2016-03-15 18:17
I got the following errors with the debug mode:

gdb --args ./bin/linear_rotation_estimator_test --logtostderr

[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from EstimateRotationsLinearTest
[ RUN      ] EstimateRotationsLinearTest.SmallTestNoNoise
linear_rotation_estimator_test: /usr/include/eigen3/Eigen/src/Core/Block.h:141: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index) [with XprType = Eigen::Matrix<double, -1, -1>; int BlockRows = -1; int BlockCols = -1; bool InnerPanel = false; Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index = long int]: Assertion `a_startRow >= 0 && blockRows >= 0 && a_startRow <= xpr.rows() - blockRows && a_startCol >= 0 && blockCols >= 0 && a_startCol <= xpr.cols() - blockCols' failed.

gdb --args ./bin/orientations_from_maximum_spanning_tree_test --logtostderr

[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from OrientationsFromViewGraph
[ RUN      ] OrientationsFromViewGraph.SmallTest
orientations_from_maximum_spanning_tree_test: /usr/include/eigen3/Eigen/src/Core/Block.h:141: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index) [with XprType = Eigen::Matrix<double, -1, -1>; int BlockRows = -1; int BlockCols = -1; bool InnerPanel = false; Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index = long int]: Assertion `a_startRow >= 0 && blockRows >= 0 && a_startRow <= xpr.rows() - blockRows && a_startCol >= 0 && blockCols >= 0 && a_startCol <= xpr.cols() - blockCols' failed.


I'll also try with the latest version of Eigen.

**Comment by sweeneychris** [comment] 2016-03-15 20:27
Could you provide the full back trace? Usually you use the "bt" command within gdb to do this

**Comment by mhsung** [comment] 2016-03-15 20:50
I just compiled with the latest version eigen, and the errors above are fixed. But now the other error comes out.

./bin/normalized_graph_cut_test --logtostderr

[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from NormalizedGraphCut
[ RUN      ] NormalizedGraphCut.SimpleGraph
/home/mhsung/Development/external/TheiaSfM/src/theia/math/graph/normalized_graph_cut_test.cc:71: Failure
Value of: 3
Expected: subgraph1.size()
Which is: 1
/home/mhsung/Development/external/TheiaSfM/src/theia/math/graph/normalized_graph_cut_test.cc:72: Failure
Value of: 3
Expected: subgraph2.size()
Which is: 5
/home/mhsung/Development/external/TheiaSfM/src/theia/math/graph/normalized_graph_cut_test.cc:81: Failure
Value of: node_1_subgraph
  Actual: 1
Expected: node_0_subgraph
Which is: 2
/home/mhsung/Development/external/TheiaSfM/src/theia/math/graph/normalized_graph_cut_test.cc:82: Failure
Value of: node_2_subgraph
  Actual: 2
Expected: node_1_subgraph
Which is: 1
/home/mhsung/Development/external/TheiaSfM/src/theia/math/graph/normalized_graph_cut_test.cc:85: Failure
Expected: (node_0_subgraph) != (node_3_subgraph), actual: 2 vs 2

Could you please take a look at this?

**Comment by sweeneychris** [comment] 2016-03-15 20:57
Are you using the master branch of Theia? I would recommend doing so if not.

I will look into this failure. This test is not randomized (i.e. it should be deterministic) so I am unsure why it is failing for you and I cannot reproduce the error on my machines.

**Comment by mhsung** [comment] 2016-03-15 22:48
Yes, I'm using the master branch, and now I just pulled from the repository but the same error happens.

**Comment by sweeneychris** [comment] 2016-03-24 19:02
I tried to recreate this error but still am not able to. The normalized graph cuts algorithm is not used in any of the reconstruction pipelines, so it is probably ok to use the library even if it is not passing.

**Comment by sweeneychris** [comment] 2016-04-04 19:40
The normalized graph cuts algorithm now uses a more stable linear solver. Could you try the master branch and see if it is working now?

**Comment by stoyanovd** [comment] 2016-04-06 15:45
Tests fail for me too.
Both before last commits (before 31 March, to be concrete) and now, too.

At least, 29, 32, 43 fails before.
And 29, 32 fails now.

And it was not deterministic all the time (i.e. fails not together and gives "100% tests passed" every second time).

**Comment by mhsung** [comment] 2016-04-06 16:59
It still fails for me as well.

**Comment by sweeneychris** [comment] 2016-04-06 17:12
@mhsung can you list the numbers of the tests that are failing still?

This behavior is totally acceptable for using Theia. As you've noticed, these tests are not deterministic and have some random behavior. When I run "make test" on my machine I can run it 100 times without getting a failed test so it is likely just parameter tuning on my end to account for various machines and whatnot.

**Comment by sweeneychris** [comment] 2016-04-06 21:23
I have submitted a patch to hopefully fix 29 and 32 (estimate_relative_pose and estimate_uncalibrated_absolute_pose) by increasing some tolerances.

Again, these tests are based on random configurations and will occasionally fail if it gets really unlucky. So I would not worry too much about the test failures, but hopefully the changes on the master branch will fix this for you.

**Comment by sweeneychris** [comment] 2016-04-27 17:11
Closing due to inactivity.

**Closed by sweeneychris** 2016-04-27 17:11 UTC
