### ISSUE TITLE
Problem running reconstruction

### ISSUE THREAD

**Issue by jasonwang01** [sweeneychris/TheiaSfM#143] opened 2017-03-21 21:32 UTC
Hi,

I successfully built the library. However, when I use runing ./bin/build_reconstruction --flagfile="", I got the following error:

Program received signal SIGABRT, Aborted.
0x00007ffff4fa5c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
0  0x00007ffff4fa5c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
1  0x00007ffff4fa9028 in __GI_abort () at abort.c:89
2  0x00007ffff58bcbbd in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
3  0x00007ffff58bab96 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
4  0x00007ffff58babe1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
5  0x00007ffff58badf8 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
6  0x00007ffff58df946 in std::__throw_ios_failure(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
7  0x00007ffff58e43e8 in std::basic_filebuf<char, std::char_traits<char> >::underflow() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
8  0x00007ffff5913275 in std::basic_streambuf<char, std::char_traits<char> >::xsgetn(char*, long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
9  0x00007ffff58e3a7e in std::basic_filebuf<char, std::char_traits<char> >::xsgetn(char*, long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
10 0x00000000004d626a in void cereal::PortableBinaryInputArchive::loadBinary<1ul>(void*, unsigned long) ()
11 0x00000000004e502f in theia::ReadMatchesAndGeometry(std::string const&, std::vector<std::string, std::allocator<std::string> >*, std::vector<theia::CameraIntrinsicsPrior, std::allocator<theia::CameraIntrinsicsPrior> >*, std::vector<theia::ImagePairMatch, std::allocator<theia::ImagePairMatch> >*) ()
12 0x00000000004d2a6c in AddMatchesToReconstructionBuilder(theia::ReconstructionBuilder*) ()
13 0x00000000004c850e in main ()

I set the path to the following directories in build_reconstruction_flags.txt 
--images=
--output_matches_file
--matches_file
--output_reconstruction
--matching_working_directory

I have no idea what I'm missing. Any ideas?

**Comment by sweeneychris** [comment] 2017-03-21 21:38
Are you supplying a flags file or actually supplying "" to the argument?

**Comment by sweeneychris** [comment] 2017-03-21 21:40
Also, try running with --logtostderr --v=2 also supplied as command lines. This should give you some informative logging information about what is going on.

**Comment by sweeneychris** [comment] 2017-03-21 22:16
Okay, I guess you edited your initial comment to include info about the flags you are passing. Make sure you actually write out --flagfile=<path_to_your_flags>/build_reconstructions_flags.txt

You've set everything to be empty! So there is no data for Theia to work with and I am not sure what you are expecting it to "reconstruct" if there is no data :)

However, Theia certainly should be catching this. I am quite surprised one of the *many* sanity checks does not cause this to halt with a useful message.

**Comment by jasonwang01** [comment] 2017-03-21 22:22
Thanks for the reply! Actually for the initial post, I am supplying the flags file. Now I am still get the same error. I believe the SIGABRT error is because of the arguments not parsed correctly, but I double checked the path and I think it is correct. Also, when I run with --logtostderr --v=2 it says:
ERROR: unknown command line flag 'logtostderr'
ERROR: unknown command line flag 'v'
Is it because I am not configuring glog correctly? I am using glog-0.3.4.

Thanks!

**Comment by sweeneychris** [comment] 2017-03-21 22:27
It seems likely that you do not have gflags linked to glog. I'd try uninstalling both, then install glog first and gflags second, ensuring that gflags links in glog.

I am a bit confused why [this line](https://github.com/sweeneychris/TheiaSfM/blob/master/applications/build_reconstruction.cc#L429) is not causing the program to halt since you have passed in empty parameters.

**Comment by jasonwang01** [comment] 2017-03-21 22:31
OK I will try linking gflags to glog. I am actually passing parameters. If I run ./bin/build_reconstruction it shows:
F0321 15:27:00.324234  5846 build_reconstruction.cc:429] Check failed: FLAGS_output_reconstruction.size() > 0 (0 vs. 0) Must specify a filepath to output the reconstruction.
*** Check failure stack trace: ***
    @     0x7fd83a054d1d  google::LogMessage::Fail()
    @     0x7fd83a056bd0  google::LogMessage::SendToLog()
    @     0x7fd83a0548e2  google::LogMessage::Flush()
    @     0x7fd83a0575ce  google::LogMessageFatal::~LogMessageFatal()
    @           0x4c857b  main
    @     0x7fd83742ff45  (unknown)
    @           0x4d2757  (unknown)
Aborted (core dumped)

When I run ./bin/build_reconstruction --flagfile=myflagsfile.txt
It gives the above SIGABRT error.

**Comment by sweeneychris** [comment] 2017-03-27 16:39
Hey Jason,

I'm pretty confident this is just a user error with supplying the flags correctly. I'm going to close this issue for now, but feel free to reopen if you're having more issues.

**Closed by sweeneychris** 2017-03-27 16:39 UTC

**Comment by charlescva** [comment] 2017-04-01 11:36
It looks like it's trying to load the matches file, and specifically that when cereal is performing a read on the matches file, there is a failure to stream it's contents in to a buffer?  (https://github.com/sweeneychris/TheiaSfM/blob/master/applications/build_reconstruction.cc#L321)

I would start by using a default flags file from _TheiaSfM/applications/build_reconstruction_flags.txt_ and save your modified copy as 'flags.txt', and pass is as follows:

TheiaSfM/theia-build/bin/build_reconstruction --flagfile=./flags.txt

Make sure you DO NOT supply "--matches_file" flag value unless you actually have successfully run a reconstruction, at which point the --output_matches_file flag will have written a file for you.  Comment it out for your first run.  Here is a minimum example of what you need to modify in the default flags file mentioned above:

--images=/home/charles/Development/theia/reconstructions/stlouishead/*.jpg
--output_matches_file=/home/charles/Development/theia/reconstructions/stlouishead/matches
#--matches_file=/home/charles/Development/theia/reconstructions/stlouishead/matches
--output_reconstruction=/home/charles/Development/theia/reconstructions/stlouishead/reconstruction

(If you set, --match_out_of_core=false)
--matching_working_directory=/home/charles/Development/theia/reconstructions/stlouishead/matching


The only thing required to make the above work is that you have *.jpg images in /home/charles/Development/theia/reconstructions/stlouishead/

I have found this issue which is similar: https://github.com/BVLC/caffe/issues/1538

I have also tried to pass a malformed matches file to build_reconstruction, but cereal caught the exception:

dd if=matches-test of=matches bs=2048 count=2
2+0 records in
2+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.000104559 s, 39.2 MB/s

TheiaSfM/theia-build/bin/build_reconstruction --flagfile=./flags.txt 
terminate called after throwing an instance of 'cereal::Exception'
  what():  Failed to read 8 bytes from input stream! Read 7
Aborted

I cannot reproduce your error in any way, with matches, without, or with corrupted matches file.
